version: '3.8'
#volumes:
 # mysql_data:
services:
  webserver:
    image: nginx:1.21.6-alpine
    container_name: aplikasi_kk_webserver
    restart: unless-stopped
    ports:
      - "8100:80"
    volumes:
      - ./:/var/www
      - .docker/nginx:/etc/nginx/conf.d
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M 

  backend:
    build:
      context: .docker/php
      dockerfile: dockerfile
    container_name: aplikasi_kk_backend
    volumes:
      - ./:/var/www
      - .docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M 

  db:
    image: mysql:8.0
    container_name: aplikasi_kk_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: app_kk
      MYSQL_ROOT_PASSWORD: secret 
    ports:
      - "4400:3306"
    volumes:
      - ./mysql:/var/lib/mysql 
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
networks:
  default:
    external: true
    name: proxy_network	
